name: ha
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - run: ls -larth
    - uses: ./.github/actions/
      with:
        name: "input from ci.yml"